service: sls-backend

package:
  include:
    - "./src/**"
  exclude:
    - node_modules/**
    - venv/**

provider:
  name: aws
  region: eu-west-1
  runtime: python3.9
  stage: api
  versionFunctions: false


functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /hello
          method: put
          cors: true

plugins:
  - serverless-python-requirements