service: sls-backend

package:
  include:
    - "./src/**"
  exclude:
    - node_modules/**
    - venv/**

custom:
  pythonRequirements:
    usePoetry: true

provider:
  name: aws
  region: eu-west-1
  runtime: python3.9
  stage: api
  versionFunctions: false
  logs:
    restApi: true


functions:
  slsFunction:
    handler: src/bin_packing.solver
    events:
      - http:
          path: /validate
          method: put
          cors: true

plugins:
  - serverless-python-requirements